name: NodeJS Github Action

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3  #checkout the repository
      - name: Use Node

        uses: actions/setup-node@v3
        with:
              node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run test
        run: npm test
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t venkatakrishnaremala/demo-app:latest .
      - name: Push Docker image
        run: docker push venkatakrishnaremala/demo-app:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]

    steps:
      - name: pull image from docker hub
        run: docker pull venkatakrishnaremala/demo-app:latest
      - name: Delete old container
        run: docker rm -f demo-app-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name demo-app-container venkatakrishnaremala/demo-app

